on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🍃 Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 🍃 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 🏗️ Install Dependencies
        run: |
          pnpm install

      - name: 👟 Start Frontend and Backend
        run: |
          docker pull ghcr.io/simplytest/banking-backend:latest
          docker run -d -p 5005:5005 -e "SIMPLYTEST_DEMO=ON" --rm --name=Banking-Backend-Demo ghcr.io/simplytest/banking-backend:latest

          pnpm run start &

      - name: ⌛ Wait for Frontend
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:4200

      - name: 🧪 End To End Tests
        run: |
          pnpm run test:e2e

      - name: 🧪 Integration Tests
        run: |
          pnpm run test:int
